spring.application.name=Mailsenser

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fazil6554@gmail.com
spring.mail.password=onwptoneambubgbl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
