spring.application.name=Mailinboxreader

spring.mail.host=imap.gmail.com
spring.mail.port=993
spring.mail.username=fazil6554@gmail.com
spring.mail.password=onwptoneambubgbl
spring.mail.properties.mail.imap.ssl.enable=true
spring.mail.properties.mail.imap.starttls.enable=true
